<?php
/**
 * @var Ryaan_BundleThumbnails_Block_Bundle_Option_Radio $this
 */
?>

<?php /** @var Mage_Catalog_Model_Product[] $selections */ ?>

<?php $option = $this->getOption(); ?>

<?php $selections  = $option->getSelections(); ?>

<?php $default     = $option->getDefaultSelection(); ?>

<?php list($defaultQty, $canChangeQty) = $this->_getDefaultValues(); ?>

<?php $tierPriceHtml = ''; ?>

<dt>
    <label<?php if ($option->getRequired()) echo ' class="required"' ?>><?php echo $this->escapeHtml($option->getTitle()) ?><?php if ($option->getRequired()) echo '<em>*</em>' ?></label>
</dt>

<dd<?php if ($option->decoratedIsLast){?> class="last"<?php }?>>

    <div class="input-box">

        <?php if ($this->_showSingle()): ?>

            <img src="<?php echo $this->getProductImage($selections[0])->resize(75) ?>" class="radio label" width="75" height="75" />

            <?php echo $this->getSelectionTitlePrice($selections[0]); ?>

            <?php if ($selections[0]->getSelectionCanChangeQty()): ?>

                <?php $tierPriceHtml = $this->getTierPriceHtml($selections[0]); ?>

            <?php endif; ?>

            <input type="hidden" name="bundle_option[<?php echo $option->getId() ?>]" value="<?php echo $selections[0]->getSelectionId() ?>" />

        <?php else:?>

            <ul class="options-list">

                <?php if (!$option->getRequired()): ?>

                    <li>

                        <input type="radio" onclick="bundle.changeSelection(this)" class="radio" id="bundle-option-<?php echo $option->getId() ?>" name="bundle_option[<?php echo $option->getId() ?>]"<?php echo ($default && $default->isSalable())?'':' checked="checked" ' ?> value=""/>

                        <span class="label">

                            <label for="bundle-option-<?php echo $option->getId() ?>">

                                <?php echo $this->__('None') ?>

                            </label>

                        </span>
                    </li>

                <?php endif; ?>

                <?php foreach ($selections as $selection): ?>

                    <?php if ($selection->getSelectionCanChangeQty() && $this->_isSelected($selection)): ?>

                        <?php $tierPriceHtml = $this->getTierPriceHtml($selection); ?>


                    <?php endif; ?>

                    <li>

                        <input type="radio" onclick="bundle.changeSelection(this)" class="radio<?php echo $option->getRequired()?' validate-one-required-by-name':'' ?> change-container-classname" id="bundle-option-<?php echo $option->getId() ?>-<?php echo $selection->getSelectionId() ?>" name="bundle_option[<?php echo $option->getId() ?>]"<?php if ($this->_isSelected($selection)) echo ' checked="checked"' ?><?php if (!$selection->isSaleable()) echo ' disabled="disabled"' ?>value="<?php echo $selection->getSelectionId() ?>"/>

                        <span class="label">

                            <label for="bundle-option-<?php echo $option->getId() ?>-<?php echo $selection->getSelectionId() ?>">

                                <img src="<?php echo $this->getProductImage($selection)->resize(75) ?>" class="radio label" width="75" height="75" />

                                <?php echo $this->getSelectionTitlePrice($selection) ?>

                            </label>

                        </span>

                        <?php if ($option->getRequired()): ?>

                            <?php echo $this->setValidationContainer('bundle-option-'.$option->getId().'-'.$selection->getSelectionId(), 'bundle-option-'.$option->getId().'-container') ?>

                        <?php endif; ?>

                    </li>

                <?php endforeach; ?>

            </ul>

            <div id="bundle-option-<?php echo $option->getId() ?>-container"></div>

        <?php endif; ?>

    </div>

    <span id="bundle-option-<?php echo $option->getId() ?>-tier-prices"> <?php echo $tierPriceHtml; ?></span>

    <span class="qty-holder">

        <label for="bundle-option-<?php echo $option->getId() ?>-qty-input"><?php echo $this->__('Qty:') ?>&nbsp;</label><input onkeyup="bundle.changeOptionQty(this, event)" onblur="bundle.changeOptionQty(this, event)" <?php if (!$canChangeQty) echo ' disabled="disabled"' ?> id="bundle-option-<?php echo $option->getId() ?>-qty-input" class="input-text qty<?php if (!$canChangeQty) echo ' qty-disabled' ?>" type="text" name="bundle_option_qty[<?php echo $option->getId() ?>]" value="<?php echo $defaultQty ?>"/>
    
    </span>

</dd>
